##############################################################################
# Step -1: ALMA archive download for NGC 4418
#
# Generated by /alma-query on 2026-04-30
# Query details: results/NGC 4418/download_query.md
#
# Scenario: C (raw ASDM (manual calibration required))
# Project:  2012.1.00377.S
# Mousid:   uid://A002/X5d7935/X14b
##############################################################################

import re
from pathlib import Path
from astroquery.alma import Alma

MOUSID = "uid://A002/X5d7935/X14b"
# Scenario C: download BOTH the raw ASDM AND the project's calibration +
# auxiliary tars. The auxiliary/calibration tars contain scriptForPI.py /
# scriptForCalibration.py which CASA needs to reduce the raw ASDM to a
# calibrated MS. Without them you have raw visibilities but no recipe.
REGEX  = r"(.*\.asdm\.sdm\.tar$|.*_auxiliary\.tar$|.*_\d+_of_\d+\.tar$)"
DEST   = Path("/Volumes/HouAstro/master/master_thesis/work_dir/NGC4418")
DEST.mkdir(parents=True, exist_ok=True)

print(f"Probing data info for {MOUSID} ...")
alma = Alma()
info = alma.get_data_info(MOUSID, expand_tarfiles=True)

def _row_size_bytes(row):
    try:
        return int(row["content_length"])
    except (ValueError, TypeError, KeyError):
        return 0


# Select URLs whose filename matches the scenario regex; track sizes.
matched = [(str(row["access_url"]), _row_size_bytes(row))
           for row in info if re.search(REGEX, str(row["access_url"]))]
matched_urls = [u for u, _ in matched]
total_bytes = sum(sz for _, sz in matched)
total_gb = total_bytes / 1e9

# Write URL list as fallback (for manual `wget -c -i download_urls.txt`).
urls_file = DEST / "download_urls.txt"
with open(urls_file, "w") as f:
    for url in matched_urls:
        f.write(f"{url}\n")
print(f"Fallback URL list written to {urls_file}")
print("  (if astroquery download fails, use: wget -c -i download_urls.txt)")
print()

print(f"Matched {len(matched_urls)} URLs, total {total_gb:.2f} GB.")
print(f"Downloading to {DEST} ...")
print(f"  regex filter: {REGEX}")
print(f"  continuation (byte-level resume): True")
print()

# `download_files` accepts direct file URLs and supports byte-level resume.
# (Do NOT use `download_and_extract_files` here — that API requires tarball
#  URLs, but expand_tarfiles=True already gave us individual file URLs.)
alma.download_files(
    matched_urls,
    savedir=str(DEST),
    cache=True,
    continuation=True,      # resume interrupted downloads at byte level
)


# NOTE (scenario C): ASDM files are delivered as tar archives. Extract manually:
#   for f in {DEST}/*.asdm.sdm.tar; do tar -xf "$f" -C {DEST}/; done
print()
print("Scenario C — extract ASDM tars manually:")
print(f'  for f in {DEST}/*.asdm.sdm.tar; do tar -xf "$f" -C {DEST}/; done')


print()
print("Done. Files in destination:")
for f in sorted(DEST.iterdir()):
    if f.is_file():
        print(f"  {f.name}  ({f.stat().st_size / 1e9:.2f} GB)")
